<?php
function fresh_puns_menu() {
  $items['path-to-ajax/%/%'] = array(
          'access arguments' => array('access content'),
          'page callback' => 'fresh_puns_ajax_callback',
          'page arguments' => array(1,2),
          'type' => MENU_CALLBACK,
  );
  return $items;
}


function fresh_puns_ajax_callback($js,$nid) {
  $node = node_load($nid);

  if ($js == 'nojs') {
    drupal_goto('node/'.$node->nid);
  }

  $build = node_view($node);
  $html = render($build);

  $commands = array();
  $commands[] = ajax_command_html('#fresh-puns-ajax-wrapper', $html);

  print ajax_render($commands);
  exit;
}
